#!/usr/bin/env sh
# https://aur.archlinux.org/cgit/aur.git/tree/microsoft-edge-dev.sh?h=microsoft-edge-dev-bin

# Make script fail if `cat` fails for some reason
set -e

# Set default value if variable is unset/null
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"

# Attempt to read a config file if it exists
if [ -r "${XDG_CONFIG_HOME}/microsoft-edge-dev-flags.conf" ]; then
  EDGE_USER_FLAGS="$(cat "$XDG_CONFIG_HOME/microsoft-edge-dev-flags.conf")"
fi

exec /opt/microsoft/msedge-dev/microsoft-edge-dev $EDGE_USER_FLAGS "$@"

